[project]
name = "pandas-sample"
version = "0.1.0"
description = "Python Pandas sample"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
